# Site settings
title: Marc Littlemore
header-img: images/home-bg.jpg
email: marc.littlemore@gmail.com
description: "Things that Marc Littlemore said."
baseurl: ""
url: "http://www.marclittlemore.com"
googleAnalyticsId: UA-810717-3
sumoMeId: "a260c264ca479174c95ace07722082ec75abbab6778c364ba7a24230cc55c451"
disqusId: "marclittlemore"
twitterUsername: "marclittlemore"
author: "Marc Littlemore"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "LICENSE"]
