# Site settings
title: Marc Littlemore
header-img: img/home-bg.jpg
email: hello@marclitlemore.com
description: "Marc Littlemore writes here."
baseurl: ""
url: "http://marclittlemore.com"
twitter_username: marclittlemore
github_username:  MarcL
instagram_username: marclittlemore
soundcloud_username: djcruze

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
