# Site settings
title: Marc Littlemore
header-img: images/home-bg.jpg
email: marc.littlemore@gmail.com
description: "Things that Marc Littlemore said."
baseurl: ""
url: "http://marclittlemore.com"
googleAnalyticsId: UA-810717-3

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "LICENSE"]
