[dev]
framework = "#static"
command = "npm run dev"

[build]
command = "npm run build"
publish = "_site"

# Edge functions
# Only run edge functions on these pages

# Add signup tag for Mailchimp newsletters
[[edge_functions]]
function = "replaceSignupQuery"
path = "/bots/sign-up-bot-building-for-beginners/"

# Add signup tag for Email Octopus newsletters
[[edge_functions]]
function = "replaceSignupQuery"
path = "/"

[[edge_functions]]
function = "replaceSignupQuery"
path = "/newsletter/"

[[edge_functions]]
function = "replaceSignupQuery"
path = "/about/"
