[dev]
framework = "#static"
command = "yarn dev"

[build]
command = "yarn build"
publish = "_site"

# Edge functions for eleventy
[[edge_functions]]
function = "eleventy-edge"
path = "/javascript-testing-beginners-course/"

[[edge_functions]]
function = "eleventy-edge"
path = "/bots/sign-up-bot-building-for-beginners/"

# Pages with the newsletter on it should run the edge function
[[edge_functions]]
function = "eleventy-edge"
path = "/"

[[edge_functions]]
function = "eleventy-edge"
path = "/newsletter/"

[[edge_functions]]
function = "eleventy-edge"
path = "/about/"
